import { GalleryItem } from "./types";

export const galleryItems: GalleryItem[] = [
  {
    id: "g-hero",
    src: "/images/kankoka-hills-candijay-bohol.jpg",
    alt: "Sweeping view of Kankoka Hills with green mountain slopes and the Candijay landscape in the background",
    caption: "The majestic contours of Kankoka Hills, Candijay, Bohol",
    width: 1920,
    height: 1280,
    category: "landscape",
  },
  {
    id: "g-dusk",
    src: "/images/dusk-16x9.jpg",
    alt: "Sunset sky in vibrant amber and warm rose tones glowing over the silhouettes of Bohol hills",
    caption: "Golden hour sunset fading into twilight dusk over the hills",
    width: 1280,
    height: 720,
    category: "sunset",
  },
  {
    id: "g-standing",
    src: "/images/standing-on-kankoka-hills-candijay-bohol.jpg",
    alt: "Visitors standing along the high ridge of Kankoka Hills gazing at the 360-degree panorama",
    caption: "Visitors taking in the 360-degree scenery from the summit",
    width: 1920,
    height: 1440,
    category: "viewpoint",
  },
  {
    id: "g-observatory",
    src: "/images/observatory-kankoka-hills-candijay-bohol.jpg",
    alt: "The viewpoint observatory deck at Kankoka Hills overlooking the green valleys",
    caption: "The hilltop observatory deck and vantage shelter",
    width: 1920,
    height: 1280,
    category: "viewpoint",
  },
  {
    id: "g-building",
    src: "/images/building-at-kankoka-hills-candijay-bohol.jpg",
    alt: "Rustic viewpoint facility nestled atop the crest of Kankoka Hills",
    caption: "Viewpoint rest stop atop the crest",
    width: 1920,
    height: 1280,
    category: "viewpoint",
  },
  {
    id: "g-view-1",
    src: "/images/view-hills-1.jpg",
    alt: "Expansive daytime vista of Candijay's undulating green ridges and rural landscape",
    caption: "Endless rolling green ridges in Candijay",
    width: 2048,
    height: 1536,
    category: "landscape",
  },
  {
    id: "g-view-2",
    src: "/images/view-hills-2.jpg",
    alt: "Vivid blue sky and contoured mountain slopes seen from Kankoka summit",
    caption: "Clear sky and lush slopes stretching toward the horizon",
    width: 2048,
    height: 1536,
    category: "landscape",
  },
  {
    id: "g-view-3",
    src: "/images/view-hills-3.jpg",
    alt: "Pristine natural countryside and tree-covered hillocks surrounding Candijay",
    caption: "Pristine countryside surrounding Kankoka Hills",
    width: 2048,
    height: 1536,
    category: "landscape",
  },
  {
    id: "g-view-4",
    src: "/images/view-hills-4.jpg",
    alt: "Sunlight and cloud shadows creating patterns across the hill ridges",
    caption: "Light and shadow dancing across the valleys",
    width: 2048,
    height: 1536,
    category: "landscape",
  },
  {
    id: "g-wide-1",
    src: "/images/wide-1.jpg",
    alt: "Ultra-wide panoramic view across the eastern Bohol mountain ranges",
    caption: "Wide-angle panoramic perspective of the Bohol ranges",
    width: 2023,
    height: 640,
    category: "panorama",
  },
  {
    id: "g-wide-2",
    src: "/images/wide-2.jpg",
    alt: "Panoramic horizon over the Candijay hills at mid-afternoon",
    caption: "Expansive panoramic horizon under the tropical sky",
    width: 2247,
    height: 640,
    category: "panorama",
  },
  {
    id: "g-wide-3",
    src: "/images/wide-3.jpg",
    alt: "Wide landscape sweep showing the undulating contours of Kankoka Hills",
    caption: "Contoured mountain profiles of eastern Bohol",
    width: 1483,
    height: 640,
    category: "panorama",
  },
];
